language: python
python:
- 2.7
- 3.2
- 3.3
- 3.4
- pypy
- pypy3
install:
- pip install -e .
- pip install -r test/requirements.txt
- pip install flake8
- | # install gevent if available.
  if python -c 'import __pypy__' 2>/dev/null
  then
    true
  elif python -c 'import sys; sys.version_info < (3,) or sys.exit(1)'
  then
    pip install gevent
  fi
- | # install yappi if available.
  if ! python -c 'import __pypy__' 2>/dev/null
  then
    pip install yappi
  fi
script:
- | # flake8
  if python -c 'import sys; sys.version_info < (3, 3) or sys.exit(1)'
  then
    EXCLUDE=profiling/remote/asyncio.py
  fi
  flake8 profiling test setup.py \
    -v --show-source --ignore=E301 --exclude=$EXCLUDE
- | # pytest
  py.test -v
